name: Build Static

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [closed]
    branches:
      - 'master'

jobs:
  build:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Prepare to build
        uses: actions/checkout@v3
      - name: prepare nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - run: yarn install
      - run: npx nuxi generate
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build
